### ISSUE TITLE
can not install requirements.txt

### ISSUE THREAD

**Issue by vitaly-zdanevich** [NuanceDev/ndev-python-http-cli#8]
`sudo pip install -r requirements.txt`:

```
Downloading/unpacking http://people.csail.mit.edu/hubert/pyaudio/packages/pyaudio-0.2.8.tar.gz (from -r requirements.txt (line 2))
  Downloading pyaudio-0.2.8.tar.gz (235kB): 235kB downloaded
  Running setup.py (path:/tmp/pip-MSYKoH-build/setup.py) egg_info for package from http://people.csail.mit.edu/hubert/pyaudio/packages/pyaudio-0.2.8.tar.gz
    
    warning: no files found matching '*.c' under directory 'test'
Requirement already satisfied (use --upgrade to upgrade): numpy in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 1))
Downloading/unpacking scikits.samplerate (from -r requirements.txt (line 3))
  Downloading scikits.samplerate-0.3.3.tar.gz (377kB): 377kB downloaded
  Running setup.py (path:/tmp/pip_build_root/scikits.samplerate/setup.py) egg_info for package scikits.samplerate
    SamplerateInfo:
      libraries samplerate not found in /usr/local/lib
      libraries samplerate not found in /usr/lib
      libraries samplerate not found in /usr/lib/i386-linux-gnu
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_root/scikits.samplerate/setup.py", line 74, in <module>
        classifiers = CLASSIFIERS,
      File "/usr/lib/python2.7/dist-packages/numpy/distutils/core.py", line 135, in setup
        config = configuration()
      File "/tmp/pip_build_root/scikits.samplerate/setup.py", line 59, in configuration
        config.add_subpackage(DISTNAME)
      File "/usr/lib/python2.7/dist-packages/numpy/distutils/misc_util.py", line 966, in add_subpackage
        caller_level = 2)
      File "/usr/lib/python2.7/dist-packages/numpy/distutils/misc_util.py", line 935, in get_subpackage
        caller_level = caller_level + 1)
      File "/usr/lib/python2.7/dist-packages/numpy/distutils/misc_util.py", line 872, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "scikits/samplerate/setup.py", line 20, in configuration
        [samplerate].""")
    numpy.distutils.system_info.NotFoundError: SRC (http://www.mega-nerd.com/SRC/) library not found.  Directories to search
    for the libraries can be specified in the site.cfg file, in section
    [samplerate].
    Complete output from command python setup.py egg_info:
    SamplerateInfo:

  libraries samplerate not found in /usr/local/lib

  libraries samplerate not found in /usr/lib

  libraries samplerate not found in /usr/lib/i386-linux-gnu

Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_root/scikits.samplerate/setup.py", line 74, in <module>

    classifiers = CLASSIFIERS,

  File "/usr/lib/python2.7/dist-packages/numpy/distutils/core.py", line 135, in setup

    config = configuration()

  File "/tmp/pip_build_root/scikits.samplerate/setup.py", line 59, in configuration

    config.add_subpackage(DISTNAME)

  File "/usr/lib/python2.7/dist-packages/numpy/distutils/misc_util.py", line 966, in add_subpackage

    caller_level = 2)

  File "/usr/lib/python2.7/dist-packages/numpy/distutils/misc_util.py", line 935, in get_subpackage

    caller_level = caller_level + 1)

  File "/usr/lib/python2.7/dist-packages/numpy/distutils/misc_util.py", line 872, in _get_configuration_from_setup_py

    config = setup_module.configuration(*args)

  File "scikits/samplerate/setup.py", line 20, in configuration

    [samplerate].""")

numpy.distutils.system_info.NotFoundError: SRC (http://www.mega-nerd.com/SRC/) library not found.  Directories to search

for the libraries can be specified in the site.cfg file, in section

[samplerate].

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/scikits.samplerate
Storing debug log for failure in /home/vitaly/.pip/pip.log

```

**Comment by wjgilmore** [comment]
FWIW I'm running a MBP with 10.12 Sierra and have the same problem.

**Comment by samueldg** [comment]
Hey @wjgilmore.

I just tried `pip install -r requirements.txt` locally (MBP + Sierra, as well) and got the same issue.

The problem is that the `scikits.samplerate` package depends on the `samplerate`library:
http://www.mega-nerd.com/SRC/

I followed the instructions on the [download page](http://www.mega-nerd.com/SRC/download.html) to install it, and then the `pip install` completed without errors.

(I then realized there's also a brew command to do the same thing documented in http://nuancedev.github.io/samples/http/python/#getting-started)

Let me know if that works for you!
